### ISSUE TITLE
FFmpeg Strict Flag

### ISSUE THREAD

**Issue by Wolveix** [gorgarp/BatchConverter#6]
The `-strict -2` flag hasn't been needed for a long time now, unless you're using an old version of FFmpeg (which used an experimental AAC codec). You'll actually get much better performance by using the libfdk_aac codec, though pre-compiled builds of FFmpeg don't have it.

Looks like a cool project! Very similar to my Plexus project, since I had the same original focus too. I've since fleshed out my tool a lot with configurable options and additional optimisations. Perhaps we could work together?

**Comment by gorgarp** [comment]
I'll pull strict. Good call.

I'd love that. Feel welcome to throw commits up etc. I intend on being as open as possible on this.

I'll close this and commit the removal of strict.

**Comment by Wolveix** [comment]
Nice. I actually meant in using my repository since my script is already established and fleshed out. If not, I would still happily make a few recommendations here :) I would highly recommend looking over the `func_encode` function of my [script](https://github.com/Wolveix/Plexus/blob/b2bdd9c658b50b066503c51c7f5dbd9796f63109/plexus) for reference material (from line 535).
